openapi: 3.1.0
info:
  title: Authentication API
  version: 1.0.0
  description: API for user authentication including login and signup.

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /auth/login:
    post:
      summary: User login
      description: Authenticates a user and returns a JWT access token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT token
                  token_type:
                    type: string
                    example: Bearer
                  expires_in:
                    type: string
                    example: "3600000"
        '401':
          description: Invalid username or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/signup:
    post:
      summary: User signup
      description: Registers a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: User created successfully
        '409':
          description: Username already taken
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          maxLength: 50
          description: Username of the user
        password:
          type: string
          maxLength: 100
          description: Password of the user

    SignupRequest:
      type: object
      required:
        - username
        - password
        - email
        - first_name
        - last_name
      properties:
        username:
          type: string
          maxLength: 50
        password:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 100
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50

    Error:
      type: object
      properties:
        error:
          type: string
          description: HTTP status or error code
        success:
          type: boolean
          description: Indicates success or failure
        message:
          type: string
          description: Human-readable error message
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
